"""added mail is_read field

Revision ID: 2e603c370844
Revises: ab8ca38f96f6
Create Date: 2026-03-10 22:39:27.558318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e603c370844'
down_revision = 'ab8ca38f96f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mail', schema=None) as batch_op:
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###
