"""empty message

Revision ID: 3c7bb46de233
Revises: 985fc2c57a5e
Create Date: 2025-11-12 17:49:01.641252

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c7bb46de233'
down_revision = '985fc2c57a5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('attachment', sa.String(length=255), nullable=True),
    sa.Column('attachment_type', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('chat_message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_message',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('sender_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('receiver_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('message', mysql.TEXT(), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('attachment', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('attachment_type', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], name=op.f('chat_message_ibfk_1')),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], name=op.f('chat_message_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('messages')
    # ### end Alembic commands ###
