"""fix

Revision ID: 4fe009febb19
Revises: 2e603c370844
Create Date: 2026-03-10 22:56:56.222032

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4fe009febb19'
down_revision = '2e603c370844'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mail', schema=None) as batch_op:
        batch_op.drop_column('is_read')

    with op.batch_alter_table('mail_recipients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mail_recipients', schema=None) as batch_op:
        batch_op.drop_column('is_read')

    with op.batch_alter_table('mail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
