"""Add timestamp column to Comment

Revision ID: 5806c4baef21
Revises: 
Create Date: 2025-10-28 13:01:10.099905

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5806c4baef21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_path', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.alter_column('contact_info',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.drop_column('message')
        batch_op.drop_column('proof_document')
        batch_op.drop_column('date_claimed')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('item_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_column('text')
        batch_op.drop_column('date_posted')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('longitude',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('lost', 'found', 'claimed'),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'lost'"))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('user', 'moderator', 'admin'),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'user'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('user', 'moderator', 'admin'),
               existing_nullable=True,
               existing_server_default=sa.text("'user'"))

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('lost', 'found', 'claimed'),
               existing_nullable=True,
               existing_server_default=sa.text("'lost'"))
        batch_op.alter_column('longitude',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_posted', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True))
        batch_op.add_column(sa.Column('text', mysql.TEXT(), nullable=False))
        batch_op.alter_column('item_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_claimed', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True))
        batch_op.add_column(sa.Column('proof_document', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('message', mysql.TEXT(), nullable=True))
        batch_op.alter_column('contact_info',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('timestamp')
        batch_op.drop_column('status')
        batch_op.drop_column('document_path')

    # ### end Alembic commands ###
