"""Add ChatMessage with attachments

Revision ID: 985fc2c57a5e
Revises: 19238d93a22d
Create Date: 2025-11-12 16:34:59.232577

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '985fc2c57a5e'
down_revision = '19238d93a22d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('attachment_type', sa.String(length=50), nullable=True))
        batch_op.alter_column('message',
               existing_type=mysql.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.drop_column('attachment_type')
        batch_op.drop_column('attachment')

    # ### end Alembic commands ###
