"""fix mail relationships

Revision ID: ab8ca38f96f6
Revises: f7e40ba51397
Create Date: 2026-03-09 17:55:26.509717

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ab8ca38f96f6'
down_revision = 'f7e40ba51397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mail_recipients',
    sa.Column('mail_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mail_id'], ['mail.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('mail_id', 'user_id')
    )
    with op.batch_alter_table('mail', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('mail_ibfk_2'), type_='foreignkey')
        batch_op.drop_column('recipient_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('mail_ibfk_2'), 'user', ['recipient_id'], ['id'])

    op.drop_table('mail_recipients')
    # ### end Alembic commands ###
