"""sync schema

Revision ID: aedee248b1ba
Revises: 0cfc1d13b435
Create Date: 2026-01-30 15:56:08.197242

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aedee248b1ba'
down_revision = '0cfc1d13b435'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reaction', schema=None) as batch_op:
        op.drop_table('reaction')
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('likes',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('dislikes',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('dislikes',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('likes',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text('0'))

    op.create_table('reaction',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('comment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('reaction_type', mysql.VARCHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], name=op.f('reaction_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('reaction_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('reaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('unique_user_comment'), ['user_id', 'comment_id'], unique=True)

    # ### end Alembic commands ###
