"""create mail table

Revision ID: d02fecb53889
Revises: e14991fd2fd7
Create Date: 2026-03-09 17:09:26.530202

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd02fecb53889'
down_revision = 'e14991fd2fd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('receiver_id', sa.Integer(), nullable=True))
        batch_op.alter_column('priority',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=10),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.alter_column('created',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.create_foreign_key(None, 'user', ['sender_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['receiver_id'], ['id'])
        batch_op.drop_column('senderid')
        batch_op.drop_column('recipientid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipientid', mysql.VARCHAR(length=1000), nullable=False))
        batch_op.add_column(sa.Column('senderid', mysql.VARCHAR(length=1000), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('created',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=1000),
               nullable=False)
        batch_op.alter_column('priority',
               existing_type=sa.String(length=10),
               type_=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_column('receiver_id')
        batch_op.drop_column('sender_id')

    # ### end Alembic commands ###
