"""add contact_info and document_paths to claim

Revision ID: e14991fd2fd7
Revises: aedee248b1ba
Create Date: 2026-01-30 17:38:20.762665

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e14991fd2fd7'
down_revision = 'aedee248b1ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_info', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('document_paths', mysql.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.drop_column('document_paths')
        batch_op.drop_column('contact_info')

    # ### end Alembic commands ###
