"""fix

Revision ID: f7e40ba51397
Revises: d02fecb53889
Create Date: 2026-03-09 17:47:35.498049

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f7e40ba51397'
down_revision = 'd02fecb53889'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_id', sa.Integer(), nullable=False))
        batch_op.alter_column('priority',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('created',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('sender_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('mail_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['recipient_id'], ['id'])
        batch_op.drop_column('receiver_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receiver_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('mail_ibfk_2'), 'user', ['receiver_id'], ['id'])
        batch_op.alter_column('sender_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('created',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('priority',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
        batch_op.drop_column('recipient_id')

    # ### end Alembic commands ###
